/* MiniJavaParser.java */
/* Generated By:JavaCC: Do not edit this line. MiniJavaParser.java */
  package Parse;
  import java.util.LinkedList;
  public class MiniJavaParser implements MiniJavaParserConstants {

/********************/
/* MiniJava Grammar */
/********************/

// Goal 	::= 	MainClass ( ClassDeclaration | ThreadDeclaration )* <EOF>
  static final public Absyn.Program Goal() throws ParseException {LinkedList<Absyn.ClassDecl> cl = new LinkedList<Absyn.ClassDecl>();
    MainClassDeclaration(cl);
    jj_consume_token(0);
{if ("" != null) return new Absyn.Program(cl);}
    throw new Error("Missing return statement in function");
}

// MainClass 	::= 	"class" Identifier "{" "public" "static" "void" "main" "(" "String" "[" "]" Identifier ")" "{" Statement "}" "}"
  static final public Absyn.ClassDecl MainClassDeclaration(LinkedList<Absyn.ClassDecl> cl) throws ParseException {Absyn.ClassDecl  cd;
 Absyn.Stmt stmt;
 Absyn.VarDecl var;
 Token name, arg;
 LinkedList<Absyn.MethodDecl> methods = new LinkedList<Absyn.MethodDecl>();
 LinkedList<Absyn.Formal> formals     = new LinkedList<Absyn.Formal>();
 LinkedList<Absyn.VarDecl> locals     = new LinkedList<Absyn.VarDecl>();
 LinkedList<Absyn.Stmt> stmts         = new LinkedList<Absyn.Stmt>();
    jj_consume_token(8);
    name = jj_consume_token(ID);
    jj_consume_token(LBRACE);
    jj_consume_token(9);
    jj_consume_token(10);
    jj_consume_token(11);
    jj_consume_token(12);
    jj_consume_token(LPAREN);
    jj_consume_token(13);
    jj_consume_token(LBRACKET);
    jj_consume_token(RBRACKET);
    arg = jj_consume_token(ID);
    jj_consume_token(RPAREN);
formals.add(new Absyn.Formal(
   new Absyn.ArrayType(
    new Absyn.IdentifierType("String")),
     arg.toString()));
    jj_consume_token(LBRACE);
    label_1:
    while (true) {
      if (jj_2_1(2147483647)) {
        ;
      } else {
        break label_1;
      }
      var = VarDeclaration();
locals.add(var);
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 15:
      case IF:
      case WHILE:
      case LBRACE:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_2;
      }
      stmt = Statement();
stmts.add(stmt);
    }
    jj_consume_token(RBRACE);
    jj_consume_token(RBRACE);
methods.add(new Absyn.MethodDecl(null, false, "main", formals,
    locals, stmts, new Absyn.IntegerLiteral(0)));
  cd = new Absyn.ClassDecl(name.toString(),
      null,
      new LinkedList<Absyn.VarDecl>(), methods);
  cl.add(cd);
  {if ("" != null) return cd;}
    throw new Error("Missing return statement in function");
}

// VarDeclaration 	::= 	Type Identifier ( = Expression )? ";"
  static final public Absyn.VarDecl VarDeclaration() throws ParseException {Absyn.Type type = null;
 Token      name = null;
 Absyn.Expr init = null;
    type = Type();
    name = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      init = Expression();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
    jj_consume_token(SEMI);
{if ("" != null) return new Absyn.VarDecl(type, name.toString(), init);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type Type() throws ParseException {Absyn.Type type;
    type = BaseType();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACKET:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      jj_consume_token(LBRACKET);
      jj_consume_token(RBRACKET);
type = new Absyn.ArrayType(type);
    }
{if ("" != null) return type;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Type BaseType() throws ParseException {Token name;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT_TYPE:{
      jj_consume_token(INT_TYPE);
{if ("" != null) return new Absyn.IntegerType();}
      break;
      }
    case BOOLEAN_TYPE:{
      jj_consume_token(BOOLEAN_TYPE);
{if ("" != null) return new Absyn.BooleanType();}
      break;
      }
    case ID:{
      name = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierType(name.toString());}
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt Statement() throws ParseException {Absyn.Stmt stmt;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LBRACE:{
      stmt = Block();
      break;
      }
    case IF:{
      stmt = IfStmt();
      break;
      }
    case WHILE:{
      stmt = WhileStmt();
      break;
      }
    case ID:{
      stmt = AssignStmt();
      break;
      }
    case 15:{
      stmt = XinuCallStatement();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return stmt;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt Block() throws ParseException {Absyn.Stmt st;
 LinkedList<Absyn.Stmt> sl = new LinkedList<Absyn.Stmt>();
    jj_consume_token(LBRACE);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 15:
      case IF:
      case WHILE:
      case LBRACE:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      st = Statement();
sl.add(st);
    }
    jj_consume_token(RBRACE);
{if ("" != null) return new Absyn.Block(sl);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt IfStmt() throws ParseException {Absyn.Expr ex;
 Absyn.Stmt st1, st2 = null;
    jj_consume_token(IF);
    jj_consume_token(LPAREN);
    ex = Expression();
    jj_consume_token(RPAREN);
    st1 = Statement();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      st2 = Statement();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
{if ("" != null) return new Absyn.If(ex, st1, st2);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt WhileStmt() throws ParseException {Absyn.Expr ex;
 Absyn.Stmt st;
    jj_consume_token(WHILE);
    jj_consume_token(LPAREN);
    ex = Expression();
    jj_consume_token(RPAREN);
    st = Statement();
{if ("" != null) return new Absyn.While(ex,st);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Stmt AssignStmt() throws ParseException {Token id;
 Absyn.Expr ex1, ex2;
    id = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASSIGN:{
      jj_consume_token(ASSIGN);
      ex1 = Expression();
      jj_consume_token(SEMI);
{if ("" != null) return new Absyn.Assign(new Absyn.Identifier(id.toString()), ex1);}
      break;
      }
    case LBRACKET:{
      jj_consume_token(LBRACKET);
      ex1 = Expression();
      jj_consume_token(RBRACKET);
      jj_consume_token(ASSIGN);
      ex2 = Expression();
      jj_consume_token(SEMI);
{if ("" != null) return new Absyn.ArrayAssign(new Absyn.Identifier(id.toString()), ex1, ex2);}
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.XinuCallStmt XinuCallStatement() throws ParseException {Token method;
 Absyn.Expr arg;
 LinkedList<Absyn.Expr> args = new LinkedList<Absyn.Expr>();
    jj_consume_token(15);
    jj_consume_token(DOT);
    method = jj_consume_token(ID);
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case THIS:
    case NEW:
    case BANG:
    case LPAREN:
    case INT:
    case STRING:
    case ID:{
      arg = Expression();
args.add(arg);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_5;
        }
        jj_consume_token(COMMA);
        arg = Expression();
args.add(arg);
      }
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
    jj_consume_token(SEMI);
{if ("" != null) return new Absyn.XinuCallStmt(method.toString(), args);}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr Expression() throws ParseException {Absyn.Expr ex;
    ex = AndExpression();
{if ("" != null) return ex;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr AndExpression() throws ParseException {Absyn.Expr ex1, ex2;
    ex1 = LessThanExpression();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 48:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_6;
      }
      jj_consume_token(48);
      ex2 = LessThanExpression();
ex1 = new Absyn.AndExpression(ex1,ex2);
    }
{if ("" != null) return ex1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr LessThanExpression() throws ParseException {Absyn.Expr ex1,ex2;
    ex1 = AdditiveExpression();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LESS:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_7;
      }
      jj_consume_token(LESS);
      ex2 = AdditiveExpression();
ex1 = new Absyn.LessThan(ex1,ex2);
    }
{if ("" != null) return ex1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr AdditiveExpression() throws ParseException {Absyn.Expr ex1,ex2;
 Token op;
    ex1 = MultiplilyExpression();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:{
        ;
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        op = jj_consume_token(PLUS);
        break;
        }
      case MINUS:{
        op = jj_consume_token(MINUS);
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      ex2 = MultiplilyExpression();
if (op.image.equals("+")){
    ex1 = new Absyn.Plus(ex1,ex2);

   }else{
    ex1 = new Absyn.Minus(ex1,ex2);
   }
    }
{if ("" != null) return ex1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr MultiplilyExpression() throws ParseException {Absyn.Expr ex1, ex2;
    ex1 = PrefixExpression();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case STAR:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_9;
      }
      jj_consume_token(STAR);
      ex2 = PrefixExpression();
ex1 = new Absyn.Times(ex1,ex2);
    }
{if ("" != null) return ex1;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr PrefixExpression() throws ParseException {Absyn.Expr ex;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BANG:{
      jj_consume_token(BANG);
      ex = PrefixExpression();
{if ("" != null) return new Absyn.Not(ex);}
      break;
      }
    case TRUE:
    case FALSE:
    case THIS:
    case NEW:
    case LPAREN:
    case INT:
    case STRING:
    case ID:{
      ex = PostfixExpression();
{if ("" != null) return ex;}
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr PostfixExpression() throws ParseException {Absyn.Expr ex, index;
 Token id;
 LinkedList<Absyn.Expr> args;
    ex = PrimaryExpression();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:
      case LBRACKET:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACKET:{
        jj_consume_token(LBRACKET);
        index = Expression();
        jj_consume_token(RBRACKET);
ex = new Absyn.ArrayLookup(ex,index);
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        if (jj_2_2(2)) {
          jj_consume_token(DOT);
          jj_consume_token(LENGTH);
ex = new Absyn.ArrayLength(ex);
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case DOT:{
            jj_consume_token(DOT);
            id = jj_consume_token(ID);
            jj_consume_token(LPAREN);
            args = ExpressionList();
            jj_consume_token(RPAREN);
ex = new Absyn.Call(ex, new Absyn.Identifier(id.image), args);
            break;
            }
          default:
            jj_la1[18] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    }
{if ("" != null) return ex;}
    throw new Error("Missing return statement in function");
}

  static final public Absyn.Expr PrimaryExpression() throws ParseException {Token t;
 Absyn.Expr ex;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      t = jj_consume_token(INT);
{if ("" != null) return new Absyn.IntegerLiteral(Integer.parseInt(t.image));}
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
{if ("" != null) return new Absyn.StringLiteral(t.image);}
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
{if ("" != null) return new Absyn.True();}
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
{if ("" != null) return new Absyn.False();}
      break;
      }
    case ID:{
      t = jj_consume_token(ID);
{if ("" != null) return new Absyn.IdentifierExp(t.image);}
      break;
      }
    case THIS:{
      jj_consume_token(THIS);
{if ("" != null) return new Absyn.This();}
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      if (jj_2_3(2)) {
        jj_consume_token(NEW);
        jj_consume_token(INT_TYPE);
        jj_consume_token(LBRACKET);
        ex = Expression();
        jj_consume_token(RBRACKET);
{if ("" != null) return new Absyn.NewArray(ex);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NEW:{
          jj_consume_token(NEW);
          t = jj_consume_token(ID);
          jj_consume_token(LPAREN);
          jj_consume_token(RPAREN);
{if ("" != null) return new Absyn.NewObject(new Absyn.Identifier(t.image));}
          break;
          }
        case LPAREN:{
          jj_consume_token(LPAREN);
          ex = Expression();
          jj_consume_token(RPAREN);
{if ("" != null) return ex;}
          break;
          }
        default:
          jj_la1[20] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public LinkedList<Absyn.Expr> ExpressionList() throws ParseException {LinkedList<Absyn.Expr> li = new LinkedList<Absyn.Expr>();
 Absyn.Expr ex;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TRUE:
    case FALSE:
    case THIS:
    case NEW:
    case BANG:
    case LPAREN:
    case INT:
    case STRING:
    case ID:{
      ex = Expression();
li.add(ex);
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          break label_11;
        }
        jj_consume_token(COMMA);
        ex = Expression();
li.add(ex);
      }
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      ;
    }
{if ("" != null) return li;}
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_3R_BaseType_185_4_18()
 {
    if (jj_scan_token(INT_TYPE)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_185_4_15()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_BaseType_185_4_18()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_186_4_19()) {
    jj_scanpos = xsp;
    if (jj_3R_BaseType_187_4_20()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_278_3_27()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) return true;
    }
    if (jj_3R_MultiplilyExpression_293_2_26()) return true;
    return false;
  }

  static private boolean jj_3R_AdditiveExpression_276_2_24()
 {
    if (jj_3R_MultiplilyExpression_293_2_26()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AdditiveExpression_278_3_27()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_Type_176_4_16()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_Type_175_2_13()
 {
    if (jj_3R_BaseType_185_4_15()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Type_176_4_16()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_LessThanExpression_267_3_25()
 {
    if (jj_scan_token(LESS)) return true;
    if (jj_3R_AdditiveExpression_276_2_24()) return true;
    return false;
  }

  static private boolean jj_3R_LessThanExpression_266_2_22()
 {
    if (jj_3R_AdditiveExpression_276_2_24()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_LessThanExpression_267_3_25()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_VarDeclaration_166_2_12()
 {
    if (jj_3R_Type_175_2_13()) return true;
    if (jj_scan_token(ID)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_VarDeclaration_166_30_14()) jj_scanpos = xsp;
    if (jj_scan_token(SEMI)) return true;
    return false;
  }

  static private boolean jj_3R_AndExpression_259_3_23()
 {
    if (jj_scan_token(48)) return true;
    if (jj_3R_LessThanExpression_266_2_22()) return true;
    return false;
  }

  static private boolean jj_3R_AndExpression_258_2_21()
 {
    if (jj_3R_LessThanExpression_266_2_22()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_AndExpression_259_3_23()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_VarDeclaration_166_2_12()) return true;
    return false;
  }

  static private boolean jj_3R_Expression_252_2_17()
 {
    if (jj_3R_AndExpression_258_2_21()) return true;
    return false;
  }

  static private boolean jj_3R_ExpressionList_343_5_47()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_Expression_252_2_17()) return true;
    return false;
  }

  static private boolean jj_3R_ExpressionList_342_3_46()
 {
    if (jj_3R_Expression_252_2_17()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ExpressionList_343_5_47()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_ExpressionList_341_2_45()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ExpressionList_342_3_46()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_334_4_42()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_Expression_252_2_17()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_333_4_41()
 {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_scan_token(NEW)) return true;
    if (jj_scan_token(INT_TYPE)) return true;
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_Expression_252_2_17()) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_331_4_40()
 {
    if (jj_scan_token(THIS)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_330_4_39()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_329_4_38()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_328_4_37()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_327_4_36()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_326_4_33()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrimaryExpression_326_4_35()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_327_4_36()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_328_4_37()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_329_4_38()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_330_4_39()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_331_4_40()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_333_4_41()) {
    jj_scanpos = xsp;
    if (jj_3R_PrimaryExpression_334_4_42()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_PrimaryExpression_326_4_35()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpression_317_4_44()
 {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_ExpressionList_341_2_45()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpression_316_4_34()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PostfixExpression_316_4_43()) {
    jj_scanpos = xsp;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3R_PostfixExpression_317_4_44()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_PostfixExpression_316_4_43()
 {
    if (jj_scan_token(LBRACKET)) return true;
    if (jj_3R_Expression_252_2_17()) return true;
    if (jj_scan_token(RBRACKET)) return true;
    return false;
  }

  static private boolean jj_3R_PostfixExpression_315_2_32()
 {
    if (jj_3R_PrimaryExpression_326_4_33()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_PostfixExpression_316_4_34()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_PrefixExpression_304_4_31()
 {
    if (jj_3R_PostfixExpression_315_2_32()) return true;
    return false;
  }

  static private boolean jj_3R_PrefixExpression_300_2_28()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_PrefixExpression_300_2_30()) {
    jj_scanpos = xsp;
    if (jj_3R_PrefixExpression_304_4_31()) return true;
    }
    return false;
  }

  static private boolean jj_3R_PrefixExpression_300_2_30()
 {
    if (jj_scan_token(BANG)) return true;
    if (jj_3R_PrefixExpression_300_2_28()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(LENGTH)) return true;
    return false;
  }

  static private boolean jj_3R_MultiplilyExpression_294_3_29()
 {
    if (jj_scan_token(STAR)) return true;
    if (jj_3R_PrefixExpression_300_2_28()) return true;
    return false;
  }

  static private boolean jj_3R_MultiplilyExpression_293_2_26()
 {
    if (jj_3R_PrefixExpression_300_2_28()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MultiplilyExpression_294_3_29()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_VarDeclaration_166_30_14()
 {
    if (jj_scan_token(ASSIGN)) return true;
    if (jj_3R_Expression_252_2_17()) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_187_4_20()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  static private boolean jj_3R_BaseType_186_4_19()
 {
    if (jj_scan_token(BOOLEAN_TYPE)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MiniJavaParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[23];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x58000,0x80000000,0x0,0x3000000,0x58000,0x58000,0x20000,0x80000000,0x0,0x4780000,0x0,0x40000000,0x30000000,0x30000000,0x8000000,0x4780000,0x0,0x0,0x0,0x380000,0x400000,0x0,0x4780000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x802,0x0,0x20,0x800,0x802,0x802,0x0,0x20,0x100,0xe08,0x10000,0x0,0x0,0x0,0x0,0xe08,0x21,0x20,0x1,0xe00,0x8,0x100,0xe08,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[3];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MiniJavaParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MiniJavaParser(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MiniJavaParser(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MiniJavaParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MiniJavaParser(MiniJavaParserTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MiniJavaParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 23; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[49];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 23; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 49; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 3; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

                               }
